import React from 'react';
import { Circle, Tooltip } from 'react-leaflet';

/**
 * ============================================================================
 * DYNAMIC RISK HEATMAP LAYER — CASCADE-NET GIS
 * ============================================================================
 * 
 * CORE RESPONSIBILITY:
 * High-performance Leaflet spatial overlay rendering continuous disaster risk
 * gradients across mountain valleys and landslide slopes.
 * 
 * VISUAL DESIGN SPECIFICATION:
 * - Subordinate Background Overlay: Renders with gentle fill opacity (0.22 - 0.42)
 *   so high-contrast markers, roads, and tactical routes remain completely legible.
 * - Semantic Color Mapping:
 *   - Critical (>= 0.80): #D64545 (Red)
 *   - High (0.60 - 0.80): #DF6D38 (Orange)
 *   - Warning (0.35 - 0.60): #C9A227 (Yellow/Amber)
 *   - Operational (< 0.35): #3D8B63 (Green)
 * 
 * ARCHITECTURAL CONTRACT:
 * RiskHeatmapLayer is strictly a presentation layer. It consumes pre-computed
 * HeatmapIntensityNode[] objects generated by riskHeatmapCalculator.js.
 * ============================================================================
 */

export default function RiskHeatmapLayer({
  nodes = [],
  visible = true,
  onSelectNode
}) {
  if (!visible || !Array.isArray(nodes) || nodes.length === 0) {
    return null;
  }

  const getHeatmapColor = (intensity) => {
    if (intensity >= 0.80) return '#D64545'; // Critical
    if (intensity >= 0.60) return '#DF6D38'; // High
    if (intensity >= 0.35) return '#C9A227'; // Warning
    return '#3D8B63';                        // Operational
  };

  return (
    <>
      {nodes.map((node) => {
        const color = getHeatmapColor(node.intensity);
        const fillOpacity = node.isPeriphery
          ? Math.max(0.12, node.intensity * 0.28)
          : Math.max(0.20, node.intensity * 0.42);

        return (
          <Circle
            key={node.id}
            center={[node.lat, node.lng]}
            radius={node.radiusMeters || 1200}
            pathOptions={{
              color: color,
              fillColor: color,
              fillOpacity: fillOpacity,
              weight: node.isPeriphery ? 0.8 : 1.5,
              opacity: node.isPeriphery ? 0.35 : 0.65,
              dashArray: node.isPeriphery ? '4, 6' : undefined,
              interactive: !node.isPeriphery // Periphery nodes don't intercept clicks
            }}
            eventHandlers={
              onSelectNode && !node.isPeriphery
                ? { click: () => onSelectNode(node) }
                : undefined
            }
          >
            {!node.isPeriphery && (
              <Tooltip sticky className="gis-tactical-tooltip-contextual">
                <span>
                  RISK HEATMAP: {node.name} [INTENSITY: {Math.round(node.intensity * 100)}%]
                </span>
              </Tooltip>
            )}
          </Circle>
        );
      })}
    </>
  );
}
